// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/FrameTransforms.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_foxglove_2fFrameTransforms_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_foxglove_2fFrameTransforms_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "foxglove/FrameTransform.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_foxglove_2fFrameTransforms_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_foxglove_2fFrameTransforms_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_foxglove_2fFrameTransforms_2eproto;
namespace foxglove {
class FrameTransforms;
struct FrameTransformsDefaultTypeInternal;
extern FrameTransformsDefaultTypeInternal _FrameTransforms_default_instance_;
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> ::foxglove::FrameTransforms* Arena::CreateMaybeMessage<::foxglove::FrameTransforms>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace foxglove {

// ===================================================================

class FrameTransforms final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:foxglove.FrameTransforms) */ {
 public:
  inline FrameTransforms() : FrameTransforms(nullptr) {}
  ~FrameTransforms() override;
  explicit PROTOBUF_CONSTEXPR FrameTransforms(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FrameTransforms(const FrameTransforms& from);
  FrameTransforms(FrameTransforms&& from) noexcept
    : FrameTransforms() {
    *this = ::std::move(from);
  }

  inline FrameTransforms& operator=(const FrameTransforms& from) {
    CopyFrom(from);
    return *this;
  }
  inline FrameTransforms& operator=(FrameTransforms&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FrameTransforms& default_instance() {
    return *internal_default_instance();
  }
  static inline const FrameTransforms* internal_default_instance() {
    return reinterpret_cast<const FrameTransforms*>(
               &_FrameTransforms_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FrameTransforms& a, FrameTransforms& b) {
    a.Swap(&b);
  }
  inline void Swap(FrameTransforms* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FrameTransforms* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FrameTransforms* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FrameTransforms>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FrameTransforms& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const FrameTransforms& from) {
    FrameTransforms::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FrameTransforms* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "foxglove.FrameTransforms";
  }
  protected:
  explicit FrameTransforms(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransformsFieldNumber = 1,
  };
  // repeated .foxglove.FrameTransform transforms = 1;
  int transforms_size() const;
  private:
  int _internal_transforms_size() const;
  public:
  void clear_transforms();
  ::foxglove::FrameTransform* mutable_transforms(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::FrameTransform >*
      mutable_transforms();
  private:
  const ::foxglove::FrameTransform& _internal_transforms(int index) const;
  ::foxglove::FrameTransform* _internal_add_transforms();
  public:
  const ::foxglove::FrameTransform& transforms(int index) const;
  ::foxglove::FrameTransform* add_transforms();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::FrameTransform >&
      transforms() const;

  // @@protoc_insertion_point(class_scope:foxglove.FrameTransforms)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::FrameTransform > transforms_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_foxglove_2fFrameTransforms_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FrameTransforms

// repeated .foxglove.FrameTransform transforms = 1;
inline int FrameTransforms::_internal_transforms_size() const {
  return _impl_.transforms_.size();
}
inline int FrameTransforms::transforms_size() const {
  return _internal_transforms_size();
}
inline ::foxglove::FrameTransform* FrameTransforms::mutable_transforms(int index) {
  // @@protoc_insertion_point(field_mutable:foxglove.FrameTransforms.transforms)
  return _impl_.transforms_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::FrameTransform >*
FrameTransforms::mutable_transforms() {
  // @@protoc_insertion_point(field_mutable_list:foxglove.FrameTransforms.transforms)
  return &_impl_.transforms_;
}
inline const ::foxglove::FrameTransform& FrameTransforms::_internal_transforms(int index) const {
  return _impl_.transforms_.Get(index);
}
inline const ::foxglove::FrameTransform& FrameTransforms::transforms(int index) const {
  // @@protoc_insertion_point(field_get:foxglove.FrameTransforms.transforms)
  return _internal_transforms(index);
}
inline ::foxglove::FrameTransform* FrameTransforms::_internal_add_transforms() {
  return _impl_.transforms_.Add();
}
inline ::foxglove::FrameTransform* FrameTransforms::add_transforms() {
  ::foxglove::FrameTransform* _add = _internal_add_transforms();
  // @@protoc_insertion_point(field_add:foxglove.FrameTransforms.transforms)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::foxglove::FrameTransform >&
FrameTransforms::transforms() const {
  // @@protoc_insertion_point(field_list:foxglove.FrameTransforms.transforms)
  return _impl_.transforms_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace foxglove

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_foxglove_2fFrameTransforms_2eproto
