// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: foxglove/TextAnnotation.proto

#include "foxglove/TextAnnotation.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace foxglove {
PROTOBUF_CONSTEXPR TextAnnotation::TextAnnotation(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.text_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/nullptr
  , /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.text_color_)*/nullptr
  , /*decltype(_impl_.background_color_)*/nullptr
  , /*decltype(_impl_.font_size_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TextAnnotationDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TextAnnotationDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TextAnnotationDefaultTypeInternal() {}
  union {
    TextAnnotation _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TextAnnotationDefaultTypeInternal _TextAnnotation_default_instance_;
}  // namespace foxglove
static ::_pb::Metadata file_level_metadata_foxglove_2fTextAnnotation_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_foxglove_2fTextAnnotation_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_foxglove_2fTextAnnotation_2eproto = nullptr;

const uint32_t TableStruct_foxglove_2fTextAnnotation_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _impl_.text_),
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _impl_.font_size_),
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _impl_.text_color_),
  PROTOBUF_FIELD_OFFSET(::foxglove::TextAnnotation, _impl_.background_color_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::foxglove::TextAnnotation)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::foxglove::_TextAnnotation_default_instance_._instance,
};

const char descriptor_table_protodef_foxglove_2fTextAnnotation_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035foxglove/TextAnnotation.proto\022\010foxglov"
  "e\032\024foxglove/Color.proto\032\025foxglove/Point2"
  ".proto\032\037google/protobuf/timestamp.proto\""
  "\324\001\n\016TextAnnotation\022-\n\ttimestamp\030\001 \001(\0132\032."
  "google.protobuf.Timestamp\022\"\n\010position\030\002 "
  "\001(\0132\020.foxglove.Point2\022\014\n\004text\030\003 \001(\t\022\021\n\tf"
  "ont_size\030\004 \001(\001\022#\n\ntext_color\030\005 \001(\0132\017.fox"
  "glove.Color\022)\n\020background_color\030\006 \001(\0132\017."
  "foxglove.Colorb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_foxglove_2fTextAnnotation_2eproto_deps[3] = {
  &::descriptor_table_foxglove_2fColor_2eproto,
  &::descriptor_table_foxglove_2fPoint2_2eproto,
  &::descriptor_table_google_2fprotobuf_2ftimestamp_2eproto,
};
static ::_pbi::once_flag descriptor_table_foxglove_2fTextAnnotation_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_foxglove_2fTextAnnotation_2eproto = {
    false, false, 342, descriptor_table_protodef_foxglove_2fTextAnnotation_2eproto,
    "foxglove/TextAnnotation.proto",
    &descriptor_table_foxglove_2fTextAnnotation_2eproto_once, descriptor_table_foxglove_2fTextAnnotation_2eproto_deps, 3, 1,
    schemas, file_default_instances, TableStruct_foxglove_2fTextAnnotation_2eproto::offsets,
    file_level_metadata_foxglove_2fTextAnnotation_2eproto, file_level_enum_descriptors_foxglove_2fTextAnnotation_2eproto,
    file_level_service_descriptors_foxglove_2fTextAnnotation_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_foxglove_2fTextAnnotation_2eproto_getter() {
  return &descriptor_table_foxglove_2fTextAnnotation_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_foxglove_2fTextAnnotation_2eproto(&descriptor_table_foxglove_2fTextAnnotation_2eproto);
namespace foxglove {

// ===================================================================

class TextAnnotation::_Internal {
 public:
  static const ::PROTOBUF_NAMESPACE_ID::Timestamp& timestamp(const TextAnnotation* msg);
  static const ::foxglove::Point2& position(const TextAnnotation* msg);
  static const ::foxglove::Color& text_color(const TextAnnotation* msg);
  static const ::foxglove::Color& background_color(const TextAnnotation* msg);
};

const ::PROTOBUF_NAMESPACE_ID::Timestamp&
TextAnnotation::_Internal::timestamp(const TextAnnotation* msg) {
  return *msg->_impl_.timestamp_;
}
const ::foxglove::Point2&
TextAnnotation::_Internal::position(const TextAnnotation* msg) {
  return *msg->_impl_.position_;
}
const ::foxglove::Color&
TextAnnotation::_Internal::text_color(const TextAnnotation* msg) {
  return *msg->_impl_.text_color_;
}
const ::foxglove::Color&
TextAnnotation::_Internal::background_color(const TextAnnotation* msg) {
  return *msg->_impl_.background_color_;
}
void TextAnnotation::clear_timestamp() {
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
}
void TextAnnotation::clear_position() {
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
}
void TextAnnotation::clear_text_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.text_color_ != nullptr) {
    delete _impl_.text_color_;
  }
  _impl_.text_color_ = nullptr;
}
void TextAnnotation::clear_background_color() {
  if (GetArenaForAllocation() == nullptr && _impl_.background_color_ != nullptr) {
    delete _impl_.background_color_;
  }
  _impl_.background_color_ = nullptr;
}
TextAnnotation::TextAnnotation(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:foxglove.TextAnnotation)
}
TextAnnotation::TextAnnotation(const TextAnnotation& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TextAnnotation* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.text_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.text_color_){nullptr}
    , decltype(_impl_.background_color_){nullptr}
    , decltype(_impl_.font_size_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_text().empty()) {
    _this->_impl_.text_.Set(from._internal_text(), 
      _this->GetArenaForAllocation());
  }
  if (from._internal_has_timestamp()) {
    _this->_impl_.timestamp_ = new ::PROTOBUF_NAMESPACE_ID::Timestamp(*from._impl_.timestamp_);
  }
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::foxglove::Point2(*from._impl_.position_);
  }
  if (from._internal_has_text_color()) {
    _this->_impl_.text_color_ = new ::foxglove::Color(*from._impl_.text_color_);
  }
  if (from._internal_has_background_color()) {
    _this->_impl_.background_color_ = new ::foxglove::Color(*from._impl_.background_color_);
  }
  _this->_impl_.font_size_ = from._impl_.font_size_;
  // @@protoc_insertion_point(copy_constructor:foxglove.TextAnnotation)
}

inline void TextAnnotation::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.text_){}
    , decltype(_impl_.timestamp_){nullptr}
    , decltype(_impl_.position_){nullptr}
    , decltype(_impl_.text_color_){nullptr}
    , decltype(_impl_.background_color_){nullptr}
    , decltype(_impl_.font_size_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.text_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.text_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TextAnnotation::~TextAnnotation() {
  // @@protoc_insertion_point(destructor:foxglove.TextAnnotation)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TextAnnotation::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.text_.Destroy();
  if (this != internal_default_instance()) delete _impl_.timestamp_;
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.text_color_;
  if (this != internal_default_instance()) delete _impl_.background_color_;
}

void TextAnnotation::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TextAnnotation::Clear() {
// @@protoc_insertion_point(message_clear_start:foxglove.TextAnnotation)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.text_.ClearToEmpty();
  if (GetArenaForAllocation() == nullptr && _impl_.timestamp_ != nullptr) {
    delete _impl_.timestamp_;
  }
  _impl_.timestamp_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.text_color_ != nullptr) {
    delete _impl_.text_color_;
  }
  _impl_.text_color_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.background_color_ != nullptr) {
    delete _impl_.background_color_;
  }
  _impl_.background_color_ = nullptr;
  _impl_.font_size_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TextAnnotation::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .google.protobuf.Timestamp timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_timestamp(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .foxglove.Point2 position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string text = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_text();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "foxglove.TextAnnotation.text"));
        } else
          goto handle_unusual;
        continue;
      // double font_size = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _impl_.font_size_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // .foxglove.Color text_color = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_text_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .foxglove.Color background_color = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_background_color(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TextAnnotation::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:foxglove.TextAnnotation)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::timestamp(this),
        _Internal::timestamp(this).GetCachedSize(), target, stream);
  }

  // .foxglove.Point2 position = 2;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // string text = 3;
  if (!this->_internal_text().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_text().data(), static_cast<int>(this->_internal_text().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "foxglove.TextAnnotation.text");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_text(), target);
  }

  // double font_size = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_font_size = this->_internal_font_size();
  uint64_t raw_font_size;
  memcpy(&raw_font_size, &tmp_font_size, sizeof(tmp_font_size));
  if (raw_font_size != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteDoubleToArray(4, this->_internal_font_size(), target);
  }

  // .foxglove.Color text_color = 5;
  if (this->_internal_has_text_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(5, _Internal::text_color(this),
        _Internal::text_color(this).GetCachedSize(), target, stream);
  }

  // .foxglove.Color background_color = 6;
  if (this->_internal_has_background_color()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::background_color(this),
        _Internal::background_color(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:foxglove.TextAnnotation)
  return target;
}

size_t TextAnnotation::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:foxglove.TextAnnotation)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string text = 3;
  if (!this->_internal_text().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_text());
  }

  // .google.protobuf.Timestamp timestamp = 1;
  if (this->_internal_has_timestamp()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.timestamp_);
  }

  // .foxglove.Point2 position = 2;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .foxglove.Color text_color = 5;
  if (this->_internal_has_text_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.text_color_);
  }

  // .foxglove.Color background_color = 6;
  if (this->_internal_has_background_color()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.background_color_);
  }

  // double font_size = 4;
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_font_size = this->_internal_font_size();
  uint64_t raw_font_size;
  memcpy(&raw_font_size, &tmp_font_size, sizeof(tmp_font_size));
  if (raw_font_size != 0) {
    total_size += 1 + 8;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TextAnnotation::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TextAnnotation::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TextAnnotation::GetClassData() const { return &_class_data_; }


void TextAnnotation::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TextAnnotation*>(&to_msg);
  auto& from = static_cast<const TextAnnotation&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:foxglove.TextAnnotation)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_text().empty()) {
    _this->_internal_set_text(from._internal_text());
  }
  if (from._internal_has_timestamp()) {
    _this->_internal_mutable_timestamp()->::PROTOBUF_NAMESPACE_ID::Timestamp::MergeFrom(
        from._internal_timestamp());
  }
  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::foxglove::Point2::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_text_color()) {
    _this->_internal_mutable_text_color()->::foxglove::Color::MergeFrom(
        from._internal_text_color());
  }
  if (from._internal_has_background_color()) {
    _this->_internal_mutable_background_color()->::foxglove::Color::MergeFrom(
        from._internal_background_color());
  }
  static_assert(sizeof(uint64_t) == sizeof(double), "Code assumes uint64_t and double are the same size.");
  double tmp_font_size = from._internal_font_size();
  uint64_t raw_font_size;
  memcpy(&raw_font_size, &tmp_font_size, sizeof(tmp_font_size));
  if (raw_font_size != 0) {
    _this->_internal_set_font_size(from._internal_font_size());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TextAnnotation::CopyFrom(const TextAnnotation& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:foxglove.TextAnnotation)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TextAnnotation::IsInitialized() const {
  return true;
}

void TextAnnotation::InternalSwap(TextAnnotation* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.text_, lhs_arena,
      &other->_impl_.text_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TextAnnotation, _impl_.font_size_)
      + sizeof(TextAnnotation::_impl_.font_size_)
      - PROTOBUF_FIELD_OFFSET(TextAnnotation, _impl_.timestamp_)>(
          reinterpret_cast<char*>(&_impl_.timestamp_),
          reinterpret_cast<char*>(&other->_impl_.timestamp_));
}

::PROTOBUF_NAMESPACE_ID::Metadata TextAnnotation::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_foxglove_2fTextAnnotation_2eproto_getter, &descriptor_table_foxglove_2fTextAnnotation_2eproto_once,
      file_level_metadata_foxglove_2fTextAnnotation_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace foxglove
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::foxglove::TextAnnotation*
Arena::CreateMaybeMessage< ::foxglove::TextAnnotation >(Arena* arena) {
  return Arena::CreateMessageInternal< ::foxglove::TextAnnotation >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
